-- MySQL Script generated by MySQL Workbench
-- Thu Sep 28 16:38:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema harcelement
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema harcelement
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `harcelement` DEFAULT CHARACTER SET utf8 ;
USE `harcelement` ;

-- -----------------------------------------------------
-- Table `harcelement`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harcelement`.`user` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `role` ENUM('admin', 'user', 'agent') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harcelement`.`institution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harcelement`.`institution` (
  `id` INT NOT NULL,
  `user_id` INT NULL,
  `grade` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `type` ENUM('police', 'gendarmerie', 'ONG') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_institution_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_institution_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `harcelement`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harcelement`.`harcelement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harcelement`.`harcelement` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harcelement`.`signalement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harcelement`.`signalement` (
  `id` INT NOT NULL,
  `user_id` INT NULL,
  `titre` VARCHAR(45) NULL,
  `contenu` LONGTEXT NULL,
  `harcelement_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_signalement_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_signalement_harcelement1_idx` (`harcelement_id` ASC) VISIBLE,
  CONSTRAINT `fk_signalement_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `harcelement`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_signalement_harcelement1`
    FOREIGN KEY (`harcelement_id`)
    REFERENCES `harcelement`.`harcelement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harcelement`.`tutoriel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harcelement`.`tutoriel` (
  `id` INT NOT NULL,
  `user_id` INT NULL,
  `link` VARCHAR(255) NULL,
  `harcelement_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tutoriel_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_tutoriel_harcelement1_idx` (`harcelement_id` ASC) VISIBLE,
  CONSTRAINT `fk_tutoriel_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `harcelement`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tutoriel_harcelement1`
    FOREIGN KEY (`harcelement_id`)
    REFERENCES `harcelement`.`harcelement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harcelement`.`publication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harcelement`.`publication` (
  `id` INT NOT NULL,
  `type` ENUM('evenementiel', 'forum') NULL,
  `user_id` INT NULL,
  `sujet` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  `contenu` LONGTEXT NULL,
  `date_heure` DATETIME NULL,
  `harcelement_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_publication_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_publication_harcelement1_idx` (`harcelement_id` ASC) VISIBLE,
  CONSTRAINT `fk_publication_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `harcelement`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publication_harcelement1`
    FOREIGN KEY (`harcelement_id`)
    REFERENCES `harcelement`.`harcelement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harcelement`.`commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harcelement`.`commentaire` (
  `id` INT NOT NULL,
  `publication_id` INT NULL,
  `user_id` INT NULL,
  `description` LONGTEXT NULL,
  `date_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commentaire_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_commentaire_publication1_idx` (`publication_id` ASC) VISIBLE,
  CONSTRAINT `fk_commentaire_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `harcelement`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaire_publication1`
    FOREIGN KEY (`publication_id`)
    REFERENCES `harcelement`.`publication` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harcelement`.`blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harcelement`.`blog` (
  `id` INT NOT NULL,
  `user_id` INT NULL,
  `titre` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `contenu` LONGTEXT NULL,
  `harcelement_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_blog_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_blog_harcelement1_idx` (`harcelement_id` ASC) VISIBLE,
  CONSTRAINT `fk_blog_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `harcelement`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blog_harcelement1`
    FOREIGN KEY (`harcelement_id`)
    REFERENCES `harcelement`.`harcelement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
